
export const sidebarContent = [
  { text: "Обложка", type: 'cover'},
  { text: "О проекте" , type: 'about'},
  { text: "Заголовок", type: 'heading' },
  { text: "Текстовый блок" },
  { text: "Изображение" },
  { text: "Галерея",  },
  { text: "Форма",  },
  { text: "Кнопка",  },
  { text: "Преимущества",  },
  { text: "Колонки", },
  { text: "Хедер",  },
  { text: "Футер",  },
  { text: "Сепаратор",  },
  { text: "Отзывы",  },
  { text: "Контакты",  },
  { text: "Услуги",  },
  { text: "Соц.сети",  },
  { text: "Партнеры",  },
  { text: "Попап",  },
  { text: "Расписание",  },
];
