import {
  faArrowRightToBracket,
  faChartArea,
  faGear,
  faGlobe,
  faHeadphones,
  faLock,
  faUser,
} from "@fortawesome/free-solid-svg-icons";

export const navlinks = [
  {
    icon: faGlobe,
    textKey: "websites",
    href: "/websites",
    text: "Мои сайты",
    id: "websites",
    data_tooltip: "websites",
    data_id: "websites",
    data_place: "top",
    margin: "mt-0",
  },
  {
    icon: faUser,
    textKey: "users",
    href: "/users",
    text: "Мои юзеры",
    id: "users",
    data_tooltip: "users",
    data_id: "users",
    data_place: "top",
    margin: "mt-4",
  },
  {
    icon: faChartArea,
    textKey: "analytics",
    href: "/analytics",
    text: "Аналитика",
    id: "analytics",
    data_tooltip: "analytics",
    data_id: "analytics",
    data_place: "top",
    margin: "mt-4",
  },
  {
    icon: faLock,
    textKey: "access",
    href: "/access",
    text: "Мой доступ",
    id: "access",
    data_tooltip: "access",
    data_id: "access",
    data_place: "top",
    margin: "mt-4",
  },
  {
    icon: faHeadphones,
    textKey: "support",
    href: "/support",
    text: "Поддержка",
    id: "support",
    data_tooltip: "support",
    data_id: "support",
    data_place: "top",
    margin: "mt-4",
  },
  {
    icon: faGear,
    textKey: "settings",
    href: "/settings",
    text: "Настройки",
    id: "settings",
    data_tooltip: "settings",
    data_id: "settings",
    data_place: "top",
    margin: "mt-4",
  },
];
