import { AppProvider } from "@shared/lib/contexts/AppContext";
import "../src/shared/styles/global.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <AppProvider>
        <body>{children}</body>
      </AppProvider>
    </html>
  );
}
