import { AppProvider } from "@shared/lib/contexts/AppContext";
import "../src/shared/styles/global.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <ThemeProvider>
        <AppProvider>
          <body>{children}</body>
        </AppProvider>
      </ThemeProvider>
    </html>
  );
}
